config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :books
  resources :reviews, only: [:create]

end

app/models/author.rb
class Author
  include Mongoid::Document
  field :given_name, type: String
  field :family_name, type: String

  has_many :books

  def full_name
    "#{given_name} #{family_name}"
  end
end

app/models/book.rb
class Book
  include Mongoid::Document
  field :title, type: String
  field :isbn, type: String
  field :abstract, type: String
  field :pages, type: Integer
  field :price, type: Float
  field :released_at, type: Date

  belongs_to :author
  embeds_many :reviews, order: :created_at.desc
end

app/models/childrens_book.rb
class ChildrensBook < Book
    field :minimum_age, type: Integer
    field :maximum_age, type: Integer
end

app/models/review.rb
class Review
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :title, type: String
  field :comment, type: String
  field :score, type: Integer
  embedded_in :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
    
    map = %Q{
      function() {
        if (this.author_id) {
          emit(this.author_id, { pages: this.pages });
        }
      }
    }

    reduce = %Q{
      function(key, values) {
        var result = { books: 0, pages: 0 };
        values.forEach(function(value) {
          result.books += 1;
          result.pages += value.pages;
        });
        return result;
      }
    }

    @author_data = {}
    Book.map_reduce(map, reduce).out(inline: true).find().to_a. each do |author|
      @author_data[author["_id"]] = author["value"]
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:given_name, :family_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all.includes(:author)
    @childrens_books = ChildrensBook.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :isbn, :abstract, :pages, :price, :released_at)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    book = Book.find(params[:review][:book_id])

    if book.reviews.create(review_params)
      redirect_to book_path(book), notice: 'Thank you for your book review!'
    else
      redirect_to book_path(book), alert: 'Your review couldn\'t be created.'
    end
  end

  private

  def review_params
    params.require(:review).permit(:name, :score, :title, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :given_name %><br>
    <%= f.text_field :given_name %>
  </div>
  <div class="field">
    <%= f.label :family_name %><br>
    <%= f.text_field :family_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Given name</th>
      <th>Family name</th>
      <th>Released books</th>
      <th>Avg. Pages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.given_name %></td>
        <td><%= author.family_name %></td>
        <td><%= @author_data[author.id] ? @author_data[author.id][:books] : 0 %></td>
        <td><%= @author_data[author.id] ? @author_data[author.id][:pages] : 0 %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Given name:</strong>
  <%= @author.given_name %>
</p>

<p>
  <strong>Family name:</strong>
  <%= @author.family_name %>
</p>

<p>
  <strong>Books:</strong>
  <ul>
    <% @author.books.each do |book| %>
      <li><%= book.title %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.collection_select :author_id, Author.all, :id, :full_name  %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br>
    <%= f.text_area :abstract %>
  </div>
  <div class="field">
    <%= f.label :pages %><br>
    <%= f.number_field :pages %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :released_at %><br>
    <%= f.date_select :released_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_review_form.html.erb
<%= form_for Review.new, { class: 'form-horizontal' } do |f| %>
  <%= f.hidden_field :book_id, value: book.id %>

  <div class="form-group row">
    <div class="col-sm-5">
      <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
    </div>
    <div class="col-sm-4">
      <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
    </div>
    <div class="col-sm-3">
      <%= f.select :score, options_for_select(["Select Score", 1,2,3,4,5], disabled: "Select Score", selected: 3), {}, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.text_area :comment, rows: 5, placeholder: 'Comment', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Children's Books</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ISBN</th>
      <th>Title</th>
      <th>Pages</th>
      <th>Price</th>
      <th>Recommended Age</th>
      <th>Released at</th>
    </tr>
  </thead>

  <tbody>
    <% @childrens_books.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= book.title %></td>
        <td><%= book.pages %></td>
        <td><%= book.price %></td>
        <td><%= book.minimum_age %>–<%= book.maximum_age %></td>
        <td><%= book.released_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h1>Listing Books</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Isbn</th>
      <th>Abstract</th>
      <th>Pages</th>
      <th>Price</th>
      <th>Released at</th>
      <th>Avg. Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author.full_name if book.author %></td>
        <td><%= book.isbn %></td>
        <td><%= book.abstract %></td>
        <td><%= book.pages %></td>
        <td><%= book.price %></td>
        <td><%= book.released_at %></td>
        <td><%= book.reviews.count > 0 ? book.reviews.avg(:score).round(1) : "–" %></td>
        <td><%= link_to 'Show', book_path(book) %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author.full_name if @book.author %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @book.abstract %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @book.pages %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Released at:</strong>
  <%= @book.released_at %>
</p>

<h2>Reviews</h2>

<%= render partial: 'review_form', locals: { book: @book } %>

<% if @book.reviews.count > 0 %>
  <% @book.reviews.each do |review| %>
    <div>
      <hr>
      <h4 style="margin-bottom: 0">(<%= review.score %>/5) <%= review.title %></h4>
      <em>by <%= review.name %> on <%= review.created_at.to_s(:short) %></em>
      <p><%= simple_format review.comment %></p>
    </div>
  <% end %>
<% else %>
  <p><em>This book has no reviews yet. Create one!</em></p>
<% end %>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mongorail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>